# Generated by Django 4.1.3 on 2022-12-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbo', '0002_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
